### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mmwachira**

### CODE REVIEW

**Review by AichaMbongo — CHANGES_REQUESTED** [review]
correct you commit convention

**Comment by mmwachira** [comment]
Corrected commit convention

**Review by Ndathi08 — APPROVED** [review]
Correct convention used

**Review by Paula-Wang — APPROVED** [review]
Good job!

**Review by UnikaMureithi — APPROVED** [review]

**Review by UnikaMureithi — APPROVED** [review]

**Pull request merged**
